runtime: nodejs16
service: default
handlers:
  - url: /
    static_files: out/index.html
    upload: out/index.html

  - url: /.*
    static_files: out/(.*\.(html))$
    upload: out/(.*\.(html))$

  - url: /
    static_dir: out
